spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.249.10.204:3306/bi
    username: BI
    password: bi123456
    type: com.alibaba.druid.pool.DruidDataSource
