spring:
  application:
    name: yubi-backend
  # 默认 dev 环境
  profiles:
    active: prod
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: 123.249.10.204
    port: 6379
    timeout: 5000
    password: yuhao123
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  rabbitmq:
    host: 123.249.10.204
    port: 5672
    password: guest
    username: guest
    virtual-host: my_vhost
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

# 鱼聪明 AI 配置
yuapi:
  client:
    access-key: 92af8w00w8d1e8iwgdt3b1hes1ac573m
    secret-key: tagt5zo0len8a3h07iwkslwe2gly32db
# todo 需替换配置
# 讯飞星火 AI 配置
xunfei:
  client:
    apiSecret: ZWZkMzNhMjE5YWZmM2RlZjk3ZmViMDA2
    apiKey: 1509ca9333dc32b28c0162763fc92222
    appid: 6d07b086
logging:
  file:
    path: /logs
